

sm_build: 
	+make -C demo sm_build

sm_build_all: 
	+make -C demo sm_build_all

sm_clean_o:
	rm -rf ./*.o
	+make -C demo sm_clean_o

##Tail
debug:

qrun:

test:

install:

clean:sm_clean_o
	+make -C demo clean


